# File: config.toml

baseURL = "https://tozhan.github.io"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Tony's Blogs"
copyright = "Â© 2020 tozhan.github.io. All rights reserved."
theme = "hugo-theme-okayish-blog"

# Provide this id to enable Google Analytics
googleAnalytics = "UA-54832953-1"

[params]


[taxonomies]

[menu]

[languages]

[languages.en-us]
languageName = "English (US)"
